title: Life in Data
description: Home to my persona data analytics projects, technical notes, and insights
remote_theme: hydecorp/hydejack@v9.0.3

plugins:
  - jekyll-include-cache

author:
  name: Mauricio Ruiz Mieles
  assets/img/lifeindata.png
