title: Life in Data
description: Home to my personal data analytics projects, technical notes, and insights
url: "https://ruizmielesmauricio.github.io"

remote_theme: hydecorp/hydejack@v9.0.3

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

accent_color: "#4f46e5"

logo: /assets/img/lifeindata.png

author:
  name: Mauricio Ruiz Mieles
  picture: /assets/img/lifeindata.png

menu:
  - title: About
    url: /about/
  - title: Machine Learning
    url: /machine-learning/
  - title: Business Intelligence
    url: /business-intelligence/
  - title: Portfolio
    url: /projects/
